spring:
  main:
    banner-mode: 'off'
server:
  servlet:
    context-path: /api/v1

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG